### ISSUE TITLE
Fails to load Angular on the Browser side.

### ISSUE THREAD

**Issue by ludoza** [nolith/kanso-angular-seed#1]
Hi,

I cloned the seed, and executed:

```
kanso install
kanso push http:/...
```

I then open the web application in the browser, and get the following error:

```
Uncaught Error: No such module: angular modules.js:49
(anonymous function) modules.js:49
kanso.moduleCache.underscore.load._.each._.forEach modules.js:15147
(anonymous function) index.html:31
```

If I modify the kanso.json package in

```
./packages/angular/kanso.json
```

And change the modules property from

```
"modules": "angular/angular.js",
```

to

```
"modules": "angular.js",
```

and move angular.js out of angular into

```
./packages/angular/angular.js
```

It works.

I understand it is most probably a problem on my side or the angular kanso package, but I found the issue in the seed so I'm reporting it here.

Kind Regards,

**Comment by matteosuppo** [comment]
Why is angular being bootstrapped manually instead of using ng-app?

I suppose there's a reason, but it works for me.

**Comment by nolith** [comment]
@matteosuppo it's bootstrapped manually because all the library are loaded asynchronously. It' based on [angular-seed index-async.html](https://github.com/angular/angular-seed/blob/master/app/index-async.html)

@ludoza so it's a problem in the angular-kanso package, I didn't had much time to work on angular recently, I'll take a look into this and I'll also update it.

Thank you

**Comment by dvdvck** [comment]
@ludoza At the index.html file, the module name to invoke angular is wrong. It should be `angular/angular`
